### PR TITLE
CSSTUDIO-2057: Beta Result List + Thread UX

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes

- Adds features to the Beta UX:
  - search result list, with date-level grouping and pagination like in current ux
  - thread ux; replies displayed in-context of current entry, like in email clients. Reply sort order matches search result list sort order
  - sort direction moved to up/down arrow above search results
  - search box is currently stubbed, search has no filters; search ux to be addressed separately

Reminder: To run, use `npm run start-beta` if you don't activate the beta feature via environment variables.
 
Screenshot 2023-12-20 at 10 13 33

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
e2e tests pass locally

**Review by georgweiss — COMMENTED** [review]
In the "conversation view" we could consider to remove the "header" when an item is expanded. In attached screen shot the time stamp of header does not match the time stamp of the entry.

Screenshot 2023-12-20 at 13 16 00

**Review by georgweiss — APPROVED** [review]

**Comment by cjenkscybercom** [comment]
Thanks for your review!
I've cleaned up date formatting in-general so they should all be consistent throughout the app, and we've added a background to the accordion summaries to make it clearer to users when they are viewing log details in the context of a thread or not (and may need to scroll down)

Screenshot 2023-12-20 at 16 06 00

**Comment by cjenkscybercom** [comment]
e2e tests pass locally

**Review by georgweiss — APPROVED** [review]
Looks good

**Pull request merged**
