### PR TITLE
remove extraneous info from readme, simplify layout

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes

- lists environment variables in table format for easier reading
- removes deployment information; there is nothing special about this frontend that differs from other React apps that isn't already noted (removes Apache Tomcat example)
- review and cleanup readme organization otherwise

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
OK, but I'd like to keep the reference to Phoebus client so that readers will have a chance to compare.

**Comment by cjenkscybercom** [comment]
> OK, but I'd like to keep the reference to Phoebus client so that readers will have a chance to compare.

Thanks for taking a look!
Could you please clarify this point, however? I'm just not finding this reference you're referring to in the original README.

**Review by georgweiss — APPROVED** [review]
Sorry, my bad. The reference URL is still there in the commit.

**Comment by cjenkscybercom** [comment]
No worries, thank you! I greatly appreciate your close eye on this.

**Pull request merged**
