### PR TITLE
More flexible way to customize Level values

### PR DESCRIPTION
**Pull request by georgweiss**
## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Review by maxfrederiksen-ess — APPROVED** [review]
Added some improvements, rest LGTM 👍

**Review by georgweiss — COMMENTED** [review]
Not in favor of console.error. I'd prefer some other way to indicate that the web app was incorrectly built/configured.

**Comment by maxfrederiksen-ess** [comment]
> Not in favor of console.error. I'd prefer some other way to indicate that the web app was incorrectly built/configured.

What would you prefer? The important part for me was to catch if there's an error, and to not re-render it multiple times.

**Comment by maxfrederiksen-ess** [comment]
Approved 👍

**Pull request merged**
