### PR TITLE
1. HTML preview was causing problems in image-processing for log details view.

### PR DESCRIPTION
**Pull request by imranau**
1. HTML preview was setting global flags that were causing problems for image-processing for Log details view. Resolved it.
2. The search string should not start with "&" character. Ideally "&" should only be in between search parameters. Fixed it.

### CODE REVIEW

**Comment by georgweiss** [comment]
@imranau , sorry, this has slipped under the radar. Will take this on as soon as possbile.

**Comment by georgweiss** [comment]
@imranau, while this may solve the original problem, I have spotted another reproduces thus:
1) Start editing a new entry.
2) Select preview.
3) Add an embedded image.
4) Select preview => image not rendered.

I have attached a screen shot of the source show a test where I first add two embedded images and the select preview. This works fine. Then I add another embedded image and select preview => third image not rendered. Once created the log entry renders fine in the main view. 

Screenshot 2021-12-17 at 07 50 31

**Comment by imranau** [comment]
In function md.core.ruler.push(), config.attachedFiles is not getting updated properly, so I am again using a global array to save attached files. And I am cleaning the global attached files array after finishing processing tokens. I have verified this recent commit. Please verify it and if you still find any issue please let me know. Thanks.

**Comment by georgweiss** [comment]
@imranau, this seems to work. But: you will need to remove function getSearchString in utils.js as that does not compile. Once that is out of the way I will merge.

**Comment by imranau** [comment]
Removed it. Thanks.

**Review by georgweiss — APPROVED** [review]

**Pull request merged**
