### PR TITLE
Refactor to styled components

### PR DESCRIPTION
**Pull request by cjenkscybercom**

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
Not sure why, but the build is failing to discover modules correctly even though this works fine locally. Investigating...

**Review by georgweiss — COMMENTED** [review]
Screenshot 2022-12-22 at 11 23 29
Layout looks a bit odd, see screen shot.

Typing in the input field for "hits per page" will invoke a search for each typed character. But when deleting chars to the point where the field is empty, the triggered search will fail as the server sees a blank char which it tries to parse as a number. Suggest search i suppressed when input field is empty.

**Comment by cjenkscybercom** [comment]
Thanks Georg! The behavior was like this before, but regardless I agree it should be debounced or similar.
I'll look into the layout bit as well, nearly forgot to touch on mobile responsiveness so I'll put some kind of barebones work into it for now until we have proper UX / device requirements.

**Comment by georgweiss** [comment]
Layout still shows considerable diff compared to current production version. Margins, spacing, split between list and og details... The log entry title is missing in the log details view.

The new log entry UI has some fields populated with (dummy?) data.

Screenshot 2022-12-22 at 14 12 24
Screenshot 2022-12-22 at 14 12 34

**Comment by cjenkscybercom** [comment]
> Layout still shows considerable diff compared to current production version. Margins, spacing, split between list and details...
> 
> The new log entry UI has some fields populated with (dummy?) data.
> 
> Screenshot 2022-12-22 at 14 12 24 Screenshot 2022-12-22 at 14 12 34

Thanks,

I'm not quite understanding what you mean by dummy data, can you clarify? My guess is you're referring to the auto-save feature that was merged into main? (saves your current log entry work)

Otherwise I changed a few small things but overall the layout etc shouldn't be drastically different? I wasn't shooting for pixel-perfect replication?

**Comment by georgweiss** [comment]
Could well be that I'm seeing my auto-save data, yes.

As for the layout:

1. The list view should not take 50% of the width on desktop.
2. The list view needs margin to the left.
3. In the details view metadata I'd like more spacing between key and value.
4. I'd like some more spacing between body and attachments drop-down.
5. Maybe use a larger font for body compared to metadata.

**Comment by cjenkscybercom** [comment]
> Could well be that I'm seeing my auto-save data, yes.
> 
> As for the layout:
> 
> 1. The list view should not take 50% of the width on desktop.
> 2. The list view needs margin to the left.
> 3. In the details view metadata I'd like more spacing between key and value.
> 4. I'd like some more spacing between body and attachments drop-down.
> 5. Maybe use a larger font for body compared to metadata.

Thanks!

I've updated the styles a bit, lemme know if all is well.

**Comment by georgweiss** [comment]
Clearly more in line with the current layout. I think this is fine.

One little snag: the default sort order seems undefined, and sorting of hit results is ascending. Should be descending by default.

**Comment by cjenkscybercom** [comment]
> Clearly more in line with the current layout. I think this is fine.
> 
> One little snag: the default sort order seems undefined, and sorting of hit results is ascending. Should be descending by default. Screenshot 2022-12-23 at 13 08 41

Good catch, thanks!

**Review by georgweiss — APPROVED** [review]

**Pull request merged**
