### PR TITLE
Csstudio 2023 edit feature

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes

- Introduces the edit feature for logs
- Refactor:
  - create and reply features are route-based rather than state-based (from /logs/edit with url params to /logs/create for creating logs, and /logs/{id}/edit or /logs/{id}/reply for edit and reply)
  - Pulled description text field + attachments into their own component and tests. Attachment editing can be disabled for the log edit screen (since the edit feature in the backend doesn't support editing log attachments)
  - move logbook and tag fields into their own components to eliminate logbook/tag prop-drilling
  - searchParam state is represented as-is as objects (rather than names); search box now looks up logbooks and tags by name, and api calls interpret the state at point of call as needed
  - many other reorganizations, hooks, etc to reduce prop-drilling
  - project structure cleanup (mostly following bulletproof react conventions)
    - customization.js:
      - moved to config/customization.js
      - urlPrefix replaced with APP_BASE_URL (deduplicating)
    - utils broken apart and pulled into sections where actually used
    - service/api files moved to one api folder
    - providers moved to providers folder
    - re-exports/configs of moment & localization moved to lib/moment.js
- Fixes:
  - log result item title can overflow and push attachment and reply icons out of view; now uses ellipsis text with mouse-over description when overflowing

Edited elements have an "edited" link that appears if there are edits:
Screenshot 2023-11-14 at 10 11 12

Clicking the link takes you to a history page, and includes a button to download the history as JSON:
Screenshot 2023-11-14 at 10 11 57

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
We appear to once-again be having issues with GitHub resources and the elastisearch container.
May disable the e2e tests for now and run/verify them manually so this 3rd-party issue that *only* is a problem in GitHub actions doesn't cause development to grind to a halt while a better solution can be found. :/

**Comment by cjenkscybercom** [comment]
e2e tests pass locally

**Comment by cjenkscybercom** [comment]
Will be removing node 14.x from the test matrix, as support ended years ago and security updates more than 6 months ago. 

We should consider removing node 16.x as well since it recently (in the past few months) also went out of support including for security patches, however I am not sure if other sites use node 16 still? 

https://endoflife.date/nodejs

You've any thoughts on this @georgweiss ?

**Comment by cjenkscybercom** [comment]
(e2e still pass locally)

**Review by georgweiss — COMMENTED** [review]
The essential pieces are there, I like the Edit button and will add it to the Phoebus client. And I like that history is shown when clicking "edited". However....

1. When editing an entry, the Phoebus client adds an asterisk to the title, see screen shot below.
2. I suspect the wrong endpoint is called when submitting the edited entry. Kunal has added a HTTP POST .../Olog/logs/{logId} for the purpose of updating.
3. Seems the Entry Type is not set in the editor when editing an entry.

Screenshot 2023-11-14 at 14 45 44

Thanks for your review!

I don't see EntryType/level in the tests so I'll add it and see if I can find if it's a bug in the FE or BE.

I do POST to `/logs/{id}?markup=commonmark` as in LogResource.java though and the e2e tests demonstrate the log is being edited, so I'm wondering if you could elaborate on what you mean by suspecting I'm calling the wrong endpoint?

I'm aware you had an asterisk but didn't do it for two reasons, and would prefer not doing it:

- Personally I find it very difficult/frustrating to click such a small link
- It's difficult to test for / isn't as accessible as the word "edited"

**Comment by cjenkscybercom** [comment]
> The essential pieces are there, I like the Edit button and will add it to the Phoebus client. And I like that history is shown when clicking "edited". However....
> 
> 1. When editing an entry, the Phoebus client adds an asterisk to the title, see screen shot below.
> 2. I suspect the wrong endpoint is called when submitting the edited entry. Kunal has added a HTTP POST .../Olog/logs/{logId} for the purpose of updating.
> 3. Seems the Entry Type is not set in the editor when editing an entry.
> 
> Screenshot 2023-11-14 at 14 45 44

Thanks for your review!

I don't see EntryType/level in the tests so I'll add it and see if I can find if it's a bug in the FE or BE. I've spotted the issue with the EntryType field not being populated when editing, so I'll fix it. Good eye, thanks!

I do POST to `/logs/{id}?markup=commonmark` as in LogResource.java though and the e2e tests demonstrate the log is being edited, so I'm wondering if you could elaborate on what you mean by suspecting I'm calling the wrong endpoint?

I'm aware you had an asterisk but didn't do it for two reasons, and would prefer not doing it:

- Personally I find it very difficult/frustrating to click such a small link
- It's difficult to test for / isn't as accessible as the word "edited"... unless the point is to deliberately introduce a dark pattern here?

**Comment by cjenkscybercom** [comment]
e2e-tests pass locally

**Review by georgweiss — APPROVED** [review]

**Pull request merged**
