### PR TITLE
Consolidate and Cleanup API Usage

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes

Consolidates and cleans up how we use the API.

- refactor: removes axios / uses entirely redux rtk
- refactor: use redux rtk api directly (<apiName>.endpoints.<endpointName>.<useQuery/useLazyQuery/useMutation/...>) rather than re-exporting queries, mutations, etc
  - In most cases we use `useQuery` and use the data directly...however in some cases we use `useLazyQuery` so we can get the result inline and do other things with it. Makes sense to just use the api directly rather than re-exporting the regular/lazy versions of each endpoint etc ad-infinitum

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
e2e tests pass locally

**Review by georgweiss — APPROVED** [review]

**Comment by cjenkscybercom** [comment]
Thank you, Georg!

**Comment by cjenkscybercom** [comment]
e2e tests pass

**Comment by cjenkscybercom** [comment]
@georgweiss would you mind giving this one last look, please? I had to resolve merge conflicts and also found/fixed an issue in the Description story (wasn't wrapped in the Redux provider as required)

**Comment by georgweiss** [comment]
Anything in particular you need me to test?

**Comment by cjenkscybercom** [comment]
> Anything in particular you need me to test?

Nope, same as before... I checked the tests pass, and verified the stories all look good.

**Comment by georgweiss** [comment]
Go ahead and merge

**Pull request merged**
