### PR TITLE
CSSTUDIO-1813: Various Tests

### PR DESCRIPTION
**Pull request by cjenkscybercom**
Adds integration and unit tests for previously manually-tested parts of the application.
Refactors a few components as part of testing/accessibility (as they go hand-in-hand)

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
Dummy question: how do you run integration tests?

**Comment by cjenkscybercom** [comment]
> Dummy question: how do you run integration tests?

Like regular tests; e.g. `npm test`

**Comment by cjenkscybercom** [comment]
Going to quick correct this merge conflict...

**Comment by georgweiss** [comment]
But where is the service expected to run? I'm not using Docker...

**Comment by cjenkscybercom** [comment]
> But where is the service expected to run? I'm not using Docker...

Are we pushing docker images of olog-service somewhere? I didn't see a docker registry specified in either the POM or the ci/cd actions. 

If you know we are pushing them somewhere, then please let me know! Either way, however, I was considering that work as a separate effort since it involves not just react but docker and ci/cd as well.

**Pull request merged**
