### PR TITLE
Rework Pills, rework spacing and alignments, Refactor properties

### PR DESCRIPTION
**Pull request by maxfrederiksen-ess**
## Summary of Changes
Title + refactor components.
@shroffk  Please don't merge until tested and approved by @georgweiss 

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Review by georgweiss — COMMENTED** [review]
- Not sure about the pills... they do not stack vertically, see screen shot.
- In my opinion the properties (e.g. when collapsed) take a bit too much vertical space.
- If a log entry has no properties, the two lines enclosing the properties part seem a bit superfluous
Screenshot 2024-10-17 at 10 08 43
Screenshot 2024-10-17 at 10 11 32
, see screen shot. Can we eliminate at least one of them?

**Comment by maxfrederiksen-ess** [comment]
> * Not sure about the pills... they do not stack vertically, see screen shot.
I thought we agreed that they should default stack in a row? They will automatically stack vertical of there are too many.
However I did notice that the "Tags" title was showing even though we didn't have any Tags to show. I guess that should not be there?
> * In my opinion the properties (e.g. when collapsed) take a bit too much vertical space.
They are smaller than the ones in production currently. Do you want them even smaller? Imo i think the size is fine, but let me know what you think.
> * If a log entry has no properties, the two lines enclosing the properties part seem a bit superfluous, see screen shot. Can we eliminate at least one of them?
Yes will do

**Comment by georgweiss** [comment]
OK, to clarify about pills: all tag pills to be rendered horizontally, but tag, logbook and entry type elements stacked vertically.
Not sure if no tags... Maybe useful to see that no tags were added?

**Comment by maxfrederiksen-ess** [comment]
Gotcha. Will fix that. 
Just feels like having a empty Tags seems a bit off. Doesn't really add any value to the user i think

**Comment by maxfrederiksen-ess** [comment]
If we do then I think we should say it explicitly in text or a specific icon etc.

**Comment by maxfrederiksen-ess** [comment]
Alright will keep

**Comment by maxfrederiksen-ess** [comment]
@georgweiss Updated now

**Review by georgweiss — APPROVED** [review]
Looks good

**Pull request merged**
