### PR TITLE
CSSTUDIO-2065: add entryType to filters

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes

- adds EntryType dropdown to filters, like in the phoebus client
- adds test for some utilities

Screenshot 2023-11-20 at 10 11 25

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
Will add #116 here

**Review by georgweiss — COMMENTED** [review]
with this PR user cannot specify multiple values for Level in the advanced search, which is actually possible currently

**Comment by cjenkscybercom** [comment]
> with this PR user cannot specify multiple values for Level in the advanced search, which is actually possible currently

It is? Am I using an outdated phoebus client?
Screenshot 2023-11-20 at 11 32 23

**Comment by georgweiss** [comment]
Good point, but that is actually wrong as current search supports multiple values.
Need to dwell on this for a moment...

**Comment by cjenkscybercom** [comment]
> Good point, but that is actually wrong as current search supports multiple values. Need to dwell on this for a moment...

Oh no worries, I was just confused since we don't have that in the phoebus client. 
We could maybe make a ticket for it? It's easy to turn on but for cases where the entry type has a space I think it is interpreted as separate words. For example, `level=Normal,Shift Start` returns results for Normal, Shift Start, *and* Shift End. I don't see anything in the search help docs about this explicitly with this field.

**Review by georgweiss — APPROVED** [review]
Let's go for this at this point.

**Pull request merged**
