### PR TITLE
CSSTUDIO-2053: add beta feature flag/stub

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes

- Adds togglable beta ui feature (opt-in only; turned off by default)
- Adds a "Try Beta UI" button if enabled
- Stubs the Beta app with a splash screen
- Refactors routing to use v6 route config, updates react-router
- Adds `npm run start-beta` for development convenience

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
e2e tests pass locally

**Review by georgweiss — APPROVED** [review]
While I'm OK with this I'd like to first make a release of the client (1.1.20) before this and upcoming PRs related to beta UI are merged.

**Comment by cjenkscybercom** [comment]
Sounds good to me! We can coordinate on Slack

**Comment by cjenkscybercom** [comment]
As clarified, this is an opt-in feature so we we can go ahead and merge this in ahead of releases.

**Pull request merged**
