### PR TITLE
Csstudio 1838 - End to End Testing (WIP)

### PR DESCRIPTION
**Pull request by cjenkscybercom**
## Summary of Changes
**WIP!! pending on work in https://github.com/Olog/phoebus-olog/pull/155 (currently uses local docker images, pending availability of images from GHCR)**

- Adds end-to-end testing for:
    - pagination
    - creating a log entry with an attachment
- Updates semantic HTML, aria, etc as necessary

## Visual Inspection

- [ ] Conformance to Markdown styles: https://olog.esss.lu.se/Olog/help/CommonmarkCheatsheet
    - [ ] ...when viewing a log entry
    - [ ] ...when previewing HTML while writing a description
    - [ ] ...when viewing a log entry in the group view
- [ ] Scroll is possible (elements don't overflow their container, and they are scrollable)
    - [ ] ...search result list
    - [ ] ...log entry group view list
    - [ ] ...log entry single view
    - [ ] ...create new log entry page
- [ ] Overall layout fills full width and height of viewport
- [ ] Pagination element doesn't overflow into other elements

### CODE REVIEW

**Comment by cjenkscybercom** [comment]
Tests will continue to fail until work on https://github.com/Olog/phoebus-olog/pull/155 is completed / docker image of the olog service is available

**Comment by cjenkscybercom** [comment]
Once the docker image is available, then per https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts I should be able to make available the screenshots and video cypress generates here in github after runs complete.

**Comment by cjenkscybercom** [comment]
SUCCESS! https://github.com/Olog/phoebus-olog-web-client/actions/runs/4323132920

@georgweiss This should be ready for review now. See above link for the test run results (note also the video + screenshots published by Cypress are available for inspection).

**Comment by cjenkscybercom** [comment]
@georgweiss Do you need any help in reviewing this?

**Comment by georgweiss** [comment]
Sorry for not commenting on this.

What are the criteria for this?

**Comment by georgweiss** [comment]
So I run all tests and all pass, regardless if Olog service is running locally or not. Does that indicate success in terms of reviewing this?

**Comment by cjenkscybercom** [comment]
> So I run all tests and all pass, regardless if Olog service is running locally or not. Does that indicate success in terms of reviewing this?

If you're running them via scripts/e2e-test.sh, then yes this is fine. You should have seen in the console output that the backend, frontend, and cypress containers were all started together. The tests would have failed if they couldn't reach something on localhost:3000

**Comment by cjenkscybercom** [comment]
> The e2e-test.sh works locally only if one has a docker daemon running, which I do not. So I think some documentation of how to use the script should be added.
> 
> Also I get test failure when running the script:
> 
> Screenshot 2023-03-16 at 12 30 01

Hi,

The updated README in this PR does state that it uses Cypress and docker compose for end-to-end testing. If you have gaps in knowledge on Docker, let me know and I can help point you in the right direction -- however, it is unnecessary to document those gaps here unless there's a specific issue to be aware of (I've done this in the past with bugs, but not for base-level knowledge such as running Docker Desktop / the daemon).

I checked for test failures locally again, and I cannot replicate the problem you are seeing (I tried twice, both with the current image I pulled, and the most recent one pulled again remotely). Without more info I cannot investigate.

> phoebus-olog-web-client-fe-olog-e2e-tests-1  |   (Run Finished)
phoebus-olog-web-client-fe-olog-e2e-tests-1  | 
phoebus-olog-web-client-fe-olog-e2e-tests-1  | 
phoebus-olog-web-client-fe-olog-e2e-tests-1  |        Spec                                              Tests  Passing  Failing  Pending  Skipped  
phoebus-olog-web-client-fe-olog-e2e-tests-1  |   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
phoebus-olog-web-client-fe-olog-e2e-tests-1  |   │ ✔  happy-paths.cy.js                        00:18        2        2        -        -        - │
phoebus-olog-web-client-fe-olog-e2e-tests-1  |   └────────────────────────────────────────────────────────────────────────────────────────────────┘
phoebus-olog-web-client-fe-olog-e2e-tests-1  |     ✔  All specs passed!                        00:18        2        2        -        -        -

**Comment by cjenkscybercom** [comment]
Thanks for the screenshare, glad to clarify this was a resource / timing problem. I've:

- added resource recommendations for docker to the readme
- increased the search range (from 30sec to 1min) in the paging search test

**Comment by cjenkscybercom** [comment]
Thanks for the screenshare, glad to clarify this was a resource / timing problem. I've:

- added resource recommendations for docker to the readme
- increased the search range (from 30sec to 1min) in the paging search test

**Review by georgweiss — APPROVED** [review]

**Comment by cjenkscybercom** [comment]
Thanks for the approval / review!

This was failing remotely because of the merged upstream changes that changed the "New Log Entry" button to a link.

**Pull request merged**
